import io
from datetime import datetime
from typing import Any, Dict, List, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from backend.models.facts import HouseholdFacts
from backend.models.scheme import SchemePack


def generate_application_pdf(scheme: SchemePack, facts: HouseholdFacts) -> bytes:
    """Generates an official-looking, pre-filled application PDF for a scheme."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "GovTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=18,
        alignment=1,  # Centered
        textColor=colors.HexColor("#1e293b"),
    )
    sub_title_style = ParagraphStyle(
        "GovSubTitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        alignment=1,
        textColor=colors.HexColor("#475569"),
    )
    section_heading = ParagraphStyle(
        "SectionHeading",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=15,
        textColor=colors.HexColor("#0f172a"),
        spaceBefore=8,
        spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "GovBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#334155"),
    )
    label_style = ParagraphStyle(
        "GovLabel",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#1e293b"),
    )

    elements = []

    # 1. Header
    elements.append(Paragraph("GOVERNMENT OF INDIA / STATE WELFARE INITIATIVE", sub_title_style))
    elements.append(Paragraph(f"APPLICATION FORM FOR {scheme.scheme_name.upper()}", title_style))
    app_ref = f"STK-{scheme.scheme_id[:3].upper()}-{datetime.now().strftime('%Y%m%d%H%M')}"
    elements.append(Paragraph(f"Application Tracking Ref: <b>{app_ref}</b> | Generated by ScholarTack Student Platform", sub_title_style))
    elements.append(Spacer(1, 8))
    elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#0284c7"), spaceAfter=10))

    # 2. Section A: Applicant & Household Demographics
    elements.append(Paragraph("SECTION A: APPLICANT & HOUSEHOLD DEMOGRAPHICS", section_heading))

    applicant_name = (facts.applicant_name.raw_value if facts.applicant_name and facts.applicant_name.raw_value else "N/A")
    applicant_age = str(facts.applicant_age.raw_value) if facts.applicant_age and facts.applicant_age.raw_value else "N/A"
    social_cat = (facts.social_category.raw_value if facts.social_category and facts.social_category.raw_value else "General / Unspecified")
    income_val = f"₹{int(facts.annual_family_income.raw_value):,}" if facts.annual_family_income and facts.annual_family_income.raw_value else "N/A"
    land_val = f"{facts.land_holding_acres.raw_value} Acres" if facts.land_holding_acres and facts.land_holding_acres.raw_value else "N/A"
    aadhaar_status = "VERIFIED (Seeded)" if facts.aadhaar_present and facts.aadhaar_present.raw_value else "Pending / Missing"

    data_a = [
        [Paragraph("Full Name of Claimant:", label_style), Paragraph(str(applicant_name), body_style),
         Paragraph("Age / Completed Yrs:", label_style), Paragraph(str(applicant_age), body_style)],
        [Paragraph("Social / Caste Category:", label_style), Paragraph(str(social_cat), body_style),
         Paragraph("Annual Family Income:", label_style), Paragraph(str(income_val), body_style)],
        [Paragraph("Agricultural Land Area:", label_style), Paragraph(str(land_val), body_style),
         Paragraph("Aadhaar KYC Status:", label_style), Paragraph(str(aadhaar_status), body_style)],
    ]

    table_a = Table(data_a, colWidths=[140, 125, 135, 130])
    table_a.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    elements.append(table_a)
    elements.append(Spacer(1, 10))

    # 3. Section B: Evidence & Proof Ledger Summary
    elements.append(Paragraph("SECTION B: DOCUMENTARY EVIDENCE & VERIFICATION LEDGER", section_heading))

    ledger_header = [
        Paragraph("Criterion / Rule", label_style),
        Paragraph("Verified Value", label_style),
        Paragraph("Document Source", label_style),
        Paragraph("Statutory Clause", label_style),
    ]
    ledger_rows = [ledger_header]

    for rule in scheme.criteria:
        fact_field = getattr(facts, rule.required_fact, None)
        val_str = str(fact_field.raw_value) if fact_field and fact_field.raw_value is not None else "Not Provided"
        doc_str = fact_field.source_image_id if fact_field and fact_field.source_image_id else "Self-Declaration"
        ledger_rows.append([
            Paragraph(rule.label, body_style),
            Paragraph(val_str, body_style),
            Paragraph(doc_str, body_style),
            Paragraph(rule.source_clause, body_style),
        ])

    table_b = Table(ledger_rows, colWidths=[160, 100, 120, 150])
    table_b.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#e2e8f0")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    elements.append(table_b)
    elements.append(Spacer(1, 10))

    # 4. Section C: Enclosures & Checklist
    elements.append(Paragraph("SECTION C: MANDATORY ATTACHMENTS CHECKLIST", section_heading))
    checklist_data = [
        [Paragraph(f" [  ] {doc.replace('_', ' ').title()}", body_style),
         Paragraph("Original required at time of physical verification", body_style)]
        for doc in scheme.application.documents_to_carry
    ]
    if checklist_data:
        table_c = Table(checklist_data, colWidths=[260, 270])
        table_c.setStyle(TableStyle([
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ]))
        elements.append(table_c)
    elements.append(Spacer(1, 10))

    # 5. Section D: Official Submission Route & Next Steps
    elements.append(Paragraph("SECTION D: OFFICIAL SUBMISSION DESTINATION", section_heading))
    route_text = (
        f"<b>Official Online Portal:</b> {scheme.application.portal_name} (<font color='#0284c7'>{scheme.application.portal_url}</font>)<br/>"
        f"<b>Designated Physical Authority:</b> {scheme.application.office_name}<br/>"
        f"<b>Entitlement Benefit:</b> {scheme.benefit}"
    )
    elements.append(Paragraph(route_text, body_style))
    elements.append(Spacer(1, 10))

    # 6. Section E: Legal Applicant Declaration
    elements.append(Paragraph("SECTION E: APPLICANT DECLARATION & SIGNATURE", section_heading))
    declaration_text = (
        "I hereby solemnly affirm that the information furnished above is true and authentic to the best of my knowledge "
        "and belief. I understand that any false statement or suppression of material facts will lead to immediate cancellation "
        "of entitlement benefits and legal proceedings under applicable law."
    )
    elements.append(Paragraph(declaration_text, body_style))
    elements.append(Spacer(1, 15))

    sig_data = [
        [Paragraph("Date: ________________________", body_style),
         Paragraph("Signature / Thumb Impression of Claimant: ____________________", body_style)],
        [Paragraph("Place: _______________________", body_style),
         Paragraph("(Countersigned by CSC Facilitator / Gram Sevak if assisted)", body_style)]
    ]
    sig_table = Table(sig_data, colWidths=[240, 290])
    sig_table.setStyle(TableStyle([
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]))
    elements.append(sig_table)

    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()


def generate_printable_ledger_pdf(scheme: SchemePack, facts: HouseholdFacts) -> bytes:
    """Generates a concise 1-page printable Proof & Eligibility Summary Ledger."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "LedgerTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=15,
        leading=19,
        alignment=1,
        textColor=colors.HexColor("#0f172a"),
    )
    sub_title = ParagraphStyle(
        "LedgerSub",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        alignment=1,
        textColor=colors.HexColor("#64748b"),
    )
    body = ParagraphStyle(
        "LedgerBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=12,
        textColor=colors.HexColor("#1e293b"),
    )
    head_cell = ParagraphStyle(
        "LedgerHead",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#0f172a"),
    )

    elements = [
        Paragraph("SCHOLARTACK ELIGIBILITY PROOF LEDGER", title_style),
        Paragraph(f"Scheme: <b>{scheme.scheme_name}</b> | Generated: {datetime.now().strftime('%d-%b-%Y %H:%M')}", sub_title),
        Paragraph(f"Entitlement: {scheme.benefit}", sub_title),
        Spacer(1, 10),
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cbd5e1"), spaceAfter=10),
    ]

    rows = [[
        Paragraph("Rule ID", head_cell),
        Paragraph("Eligibility Criterion", head_cell),
        Paragraph("Extracted Value", head_cell),
        Paragraph("Provenance", head_cell),
        Paragraph("Proving Document", head_cell),
        Paragraph("Legal Reference Clause", head_cell),
    ]]

    for rule in scheme.criteria:
        f = getattr(facts, rule.required_fact, None)
        val = str(f.raw_value) if f and f.raw_value is not None else "Missing"
        prov = str(f.provenance.value if f else "UNKNOWN")
        doc_src = f.source_image_id if f and f.source_image_id else "None"
        rows.append([
            Paragraph(rule.rule_id, body),
            Paragraph(rule.label, body),
            Paragraph(val, body),
            Paragraph(prov, body),
            Paragraph(doc_src, body),
            Paragraph(rule.source_clause, body),
        ])

    table = Table(rows, colWidths=[55, 140, 75, 75, 95, 100])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 15))

    footer_text = (
        "<b>Audit Note:</b> This ledger provides a deterministic evaluation of statutory criteria against extracted facts. "
        "ScholarTack does not replace the designated government authority."
    )
    elements.append(Paragraph(footer_text, sub_title))

    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()


def generate_student_report_pdf(
    student: Dict[str, Any],
    eligible_scholarships: List[Dict[str, Any]],
    tracked_apps: List[Dict[str, Any]],
    doc_checklist: List[Dict[str, Any]],
) -> bytes:
    """Generates an institutional A4 printable ScholarTack Scholarship Eligibility & Status Report."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "InstTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=15,
        leading=19,
        textColor=colors.HexColor("#0f172a"),
    )
    sub_title = ParagraphStyle(
        "InstSub",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#475569"),
    )
    sec_head = ParagraphStyle(
        "InstSecHead",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10.5,
        leading=14,
        textColor=colors.HexColor("#0284c7"),
        spaceBefore=10,
        spaceAfter=4,
    )
    cell_head = ParagraphStyle(
        "InstCellHead",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#1e293b"),
    )
    cell_body = ParagraphStyle(
        "InstCellBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#334155"),
    )
    cell_bold = ParagraphStyle(
        "InstCellBold",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#0f172a"),
    )
    badge_green = ParagraphStyle(
        "BadgeGreen",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#059669"),
    )
    badge_amber = ParagraphStyle(
        "BadgeAmber",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#d97706"),
    )

    elements = []

    # 1. Institutional Header
    header_data = [
        [
            Paragraph("<b>SCHOLARTACK</b> | Student Scholarship Intelligence Platform", sub_title),
            Paragraph(f"Ref: <b>STK-REP-{datetime.now().strftime('%Y%m%d-%H%M')}</b>", ParagraphStyle("RefRight", parent=sub_title, alignment=2)),
        ],
        [
            Paragraph("SCHOLARSHIP ELIGIBILITY & STATUS REPORT", title_style),
            Paragraph(f"Date: {datetime.now().strftime('%d %B %Y')}", ParagraphStyle("DateRight", parent=sub_title, alignment=2)),
        ],
    ]
    header_table = Table(header_data, colWidths=[360, 163])
    header_table.setStyle(TableStyle([
        ('TOPPADDING', (0, 0), (-1, -1), 2),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
    ]))
    elements.append(header_table)
    elements.append(Spacer(1, 4))
    elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#0284c7"), spaceAfter=8))

    # 2. Section: Student Profile
    elements.append(Paragraph("1. STUDENT PROFILE & ELIGIBILITY ATTRIBUTES", sec_head))
    
    name = student.get("applicant_name") or student.get("name") or "Student Candidate"
    usn = student.get("student_id") or student.get("usn") or "Not Assigned"
    college = student.get("institution_name") or student.get("college") or "Not Specified"
    age = str(student.get("applicant_age") or student.get("age") or "19")
    gender = str(student.get("gender") or "Not Specified").capitalize()
    course = str(student.get("course_name") or student.get("education_level") or "Undergraduate")
    year = str(student.get("year_of_study") or "2nd Year")
    category = str(student.get("social_category") or "General")
    income = f"₹{int(float(student.get('annual_family_income', 250000))):,}" if student.get("annual_family_income") is not None else "N/A"
    marks = f"{student.get('academic_percentage', 75)}%" + (f" (CGPA: {student.get('cgpa')})" if student.get("cgpa") else "")
    state = str(student.get("domicile_state") or "Karnataka")
    aadhaar_status = "Linked & Verified" if student.get("aadhaar_present", True) else "Pending KYC"
    bank_status = "Active NPCI DBT" if student.get("bank_account_present", True) else "Not Seeded"

    prof_data = [
        [Paragraph("Candidate Name:", cell_head), Paragraph(name, cell_bold), Paragraph("USN / Student ID:", cell_head), Paragraph(usn, cell_bold)],
        [Paragraph("College / Institution:", cell_head), Paragraph(college, cell_bold), Paragraph("Enrolled Course:", cell_head), Paragraph(f"{course} ({year})", cell_body)],
        [Paragraph("Social Category:", cell_head), Paragraph(category, cell_body), Paragraph("Annual Family Income:", cell_head), Paragraph(income, cell_body)],
        [Paragraph("Academic Performance:", cell_head), Paragraph(marks, cell_bold), Paragraph("Domicile State:", cell_head), Paragraph(state, cell_body)],
        [Paragraph("Age & Gender:", cell_head), Paragraph(f"{age} Yrs / {gender}", cell_body), Paragraph("Aadhaar & Bank DBT:", cell_head), Paragraph(f"{aadhaar_status} / {bank_status}", cell_body)],
    ]
    prof_table = Table(prof_data, colWidths=[110, 150, 110, 153])
    prof_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#f4f8f5")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2ebe5")),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
    ]))
    elements.append(prof_table)
    elements.append(Spacer(1, 6))

    # 3. Section: Institutional Summary Stats
    total_matched = len(eligible_scholarships)
    active_tracked = len(tracked_apps)
    verified_docs = sum(1 for d in doc_checklist if str(d.get("status", "")).lower() in ("verified", "uploaded"))
    total_docs = max(len(doc_checklist), 1)
    readiness_pct = round((verified_docs / total_docs) * 100)

    summary_data = [
        [
            Paragraph("Total Matched Schemes", cell_head),
            Paragraph("Document Readiness", cell_head),
            Paragraph("Active Applications", cell_head),
            Paragraph("Profile Verification", cell_head),
        ],
        [
            Paragraph(f"<b>{total_matched} Schemes</b>", cell_bold),
            Paragraph(f"<b>{readiness_pct}% Complete</b>", badge_green if readiness_pct >= 80 else badge_amber),
            Paragraph(f"<b>{active_tracked} Tracked</b>", cell_bold),
            Paragraph("<b>Deterministic Verified</b>", badge_green),
        ],
    ]
    sum_table = Table(summary_data, colWidths=[130, 130, 130, 133])
    sum_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
        ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor("#ffffff")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
    ]))
    elements.append(sum_table)
    elements.append(Spacer(1, 6))

    # 4. Section: Eligible & Matched Schemes
    elements.append(Paragraph("2. STATUTORY SCHOLARSHIP MATCHES & ELIGIBILITY", sec_head))
    sch_rows = [[
        Paragraph("Scheme Name", cell_head),
        Paragraph("Award Amount", cell_head),
        Paragraph("Authority / Portal", cell_head),
        Paragraph("Deadline", cell_head),
        Paragraph("Status", cell_head),
    ]]

    if eligible_scholarships:
        for sch in eligible_scholarships[:6]:
            s_name = sch.get("scheme_name") or sch.get("name") or "Scholarship"
            s_amt = sch.get("award_amount") or sch.get("benefit") or "Variable"
            s_auth = sch.get("authority") or "Central/State Portal"
            if len(s_auth) > 35:
                s_auth = s_auth[:32] + "..."
            s_dl = sch.get("deadline") or "Open"
            s_match = f"{sch.get('match_score', 100)}% Match"

            sch_rows.append([
                Paragraph(s_name, cell_bold),
                Paragraph(s_amt, cell_body),
                Paragraph(s_auth, cell_body),
                Paragraph(s_dl, cell_body),
                Paragraph(s_match, badge_green),
            ])
    else:
        sch_rows.append([
            Paragraph("No active eligible schemes matched yet. Complete your profile attributes to calculate eligibility.", cell_body),
            Paragraph("-", cell_body), Paragraph("-", cell_body), Paragraph("-", cell_body), Paragraph("-", cell_body),
        ])

    sch_table = Table(sch_rows, colWidths=[190, 100, 120, 55, 58])
    sch_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
    ]))
    elements.append(sch_table)
    elements.append(Spacer(1, 6))

    # 5. Section: Document Checklist Audit
    elements.append(Paragraph("3. STATUTORY DOCUMENT READINESS CHECKLIST", sec_head))
    doc_rows = [[
        Paragraph("Document Name", cell_head),
        Paragraph("Issuing Authority", cell_head),
        Paragraph("Required For", cell_head),
        Paragraph("Status", cell_head),
    ]]

    sample_docs = doc_checklist if doc_checklist else [
        {"name": "Aadhaar Card (UIDAI)", "authority": "UIDAI", "required_by": "All Statutory Schemes", "status": "Verified"},
        {"name": "College Admission / Bonafide", "authority": "Enrolled Institution", "required_by": "NSP & AICTE Schemes", "status": "Verified"},
        {"name": "Class 10th / 12th Marksheet", "authority": "State / CBSE / ICSE Board", "required_by": "Merit Verification", "status": "Uploaded"},
        {"name": "Income Certificate", "authority": "Revenue Dept / Tehsildar", "required_by": "Means Verification (<= ₹2.5L - ₹8L)", "status": "Pending"},
        {"name": "NPCI Aadhaar-Seeded Bank Account", "authority": "Scheduled Commercial Bank", "required_by": "DBT Fund Disbursement", "status": "Verified"},
    ]

    for d in sample_docs[:5]:
        d_name = d.get("name") or "Document"
        d_auth = d.get("authority") or "Competent Authority"
        d_req = d.get("required_by") or "Eligible Schemes"
        d_stat = str(d.get("status") or "Required").capitalize()
        status_style = badge_green if d_stat.lower() in ("verified", "uploaded") else badge_amber

        doc_rows.append([
            Paragraph(d_name, cell_body),
            Paragraph(d_auth, cell_body),
            Paragraph(d_req, cell_body),
            Paragraph(d_stat, status_style),
        ])

    doc_table = Table(doc_rows, colWidths=[160, 130, 150, 83])
    doc_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
    ]))
    elements.append(doc_table)
    elements.append(Spacer(1, 6))

    # 6. Section: Application Tracking Pipeline
    elements.append(Paragraph("4. ACTIVE APPLICATION PIPELINE STATUS", sec_head))
    app_rows = [[
        Paragraph("Scheme", cell_head),
        Paragraph("Stage / Status", cell_head),
        Paragraph("Application Ref #", cell_head),
        Paragraph("Submission / Target", cell_head),
        Paragraph("Remarks / Action", cell_head),
    ]]

    if tracked_apps:
        for a in tracked_apps[:4]:
            a_name = a.get("scheme_name") or "Scheme Application"
            if len(a_name) > 30:
                a_name = a_name[:28] + "..."
            a_status = str(a.get("status") or "saved").replace("_", " ").title()
            a_num = a.get("application_number") or "Pending Gen"
            a_date = a.get("applied_date") or a.get("deadline") or "2026-10-15"
            a_notes = a.get("notes") or "Targeting next submission window"
            if len(a_notes) > 35:
                a_notes = a_notes[:32] + "..."

            app_rows.append([
                Paragraph(a_name, cell_bold),
                Paragraph(a_status, badge_green if a_status in ("Submitted", "Approved", "Disbursed") else badge_amber),
                Paragraph(a_num, cell_body),
                Paragraph(a_date, cell_body),
                Paragraph(a_notes, cell_body),
            ])
    else:
        app_rows.append([
            Paragraph("No applications currently tracked. Save eligible schemes to start tracking.", cell_body),
            Paragraph("-", cell_body), Paragraph("-", cell_body), Paragraph("-", cell_body), Paragraph("-", cell_body),
        ])

    app_table = Table(app_rows, colWidths=[150, 85, 95, 75, 118])
    app_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
    ]))
    elements.append(app_table)
    elements.append(Spacer(1, 8))

    # 7. Official Notice & Disclaimer Footer
    footer_text = (
        "<b>Important Statutory Notice:</b> Direct Benefit Transfer (DBT) requires active NPCI bank seeding with Aadhaar. "
        "Students must ensure One-Time Registration (OTR) is completed on the National Scholarship Portal (scholarships.gov.in) "
        "and physical documents are endorsed by their college nodal officer.<br/>"
        "<b>Disclaimer:</b> ScholarTack is an institutional student intelligence platform designed to assist in statutory scheme "
        "matching and document readiness. It does not replace designated government portals or approval bodies."
    )
    elements.append(Paragraph(footer_text, ParagraphStyle("FooterDisclaimer", parent=sub_title, fontSize=7.5, leading=10, textColor=colors.HexColor("#64748b"))))

    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()

